### ISSUE TITLE
Make a GitHub Action

### ISSUE THREAD

**Issue by frostming** [yihong0618/github-readme-stats#1]
This repo is interesting, a GitHub Action would be great for others to include in their profile page.

Currently, based on the implementation language, a docker image should do the trick. But ideally, using JavaScript/TypeScript will speed up a lot. That can be done in the future though.

I can help to do the first step.

**Comment by yihong0618** [comment]
> This repo is interesting, a GitHub Action would be great for others to include in their profile page.
> 
> Currently, based on the implementation language, a docker image should do the trick. But ideally, using JavaScript/TypeScript will speed up a lot. That can be done in the future though.
> 
> I can help to do the first step.

Now its has GitHub Action.~

**Comment by frostming** [comment]
Oh great, can you point me to the correct place?

**Comment by yihong0618** [comment]
> Oh great, can you point me to the correct place?

Sorry I maybe I missed your point, you mean GItHub Actions in Market place or something?

That would be great, Thanks.
