### ISSUE TITLE
Q: how to show the image of My GitHub Status

### ISSUE THREAD

**Issue by ThaddeusJiang** [yihong0618/github-readme-stats#6]
like this
![image](https://user-images.githubusercontent.com/17308201/112084165-ad79e180-8bcb-11eb-9de2-446e2b985480.png)

I have forked your repo and modified the `yml`, didn't find the image.

https://github.com/ThaddeusJiang/github-readme-stats

**Comment by yihong0618** [comment]
@ThaddeusJiang 开始有来的，后来给去掉了。哈哈
<img align="middle" src="https://github-readme-stats-1.yihong0618.vercel.app/api?username=ThaddeusJiang&show_icons=true&&&hide_title=true" />


你在 readme 最上面加这一句就行
```
<img align="middle" src="https://github-readme-stats-1.yihong0618.vercel.app/api?username=ThaddeusJiang&show_icons=true&&&hide_title=true" />
```

**Comment by yihong0618** [comment]
@ThaddeusJiang 
是这个项目 https://github.com/anuraghazra/github-readme-stats

核心是替换注释中的文本，所以你加在上面不会影响你重新生成。

**Comment by ThaddeusJiang** [comment]
@yihong0618 ok 明白了，我的 .github 也用了这个 repo。
thank you
